#!/usr/bin/env python

import sys

from rqt_publisherpkg.my_module import Publisher
from rqt_gui.main import Main

plugin = 'rqt_publisherpkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
