#!/usr/bin/env python

import sys

from rqt_batterypkg.my_module import battery
from rqt_gui.main import Main

plugin = 'rqt_batterypkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
