#!/usr/bin/env python

import sys

from rqt_squadronpkg.my_module import Squadron
from rqt_gui.main import Main

plugin = 'rqt_squadronpkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
